services:
  node:
    platform: linux/x86_64
    image: "bugs_node:latest"
    container_name: "demo_node"
    volumes:
      - ./config/demo.js:/home/web/demo.js
      - ./pdf:/home/web/pdf
      - ./tmp:/tmp
    depends_on:
      - web
    extra_hosts:
      - host.docker.internal:host-gateway

  web:
    image: nginx:latest
    container_name: "demo_nginx"
    restart: unless-stopped
    volumes:
      - ./html:/usr/share/nginx/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
    environment:
      VIRTUAL_HOST: demo.test